project:
  type: book
  output-dir: docs

book:
  title: "Interactive Investments Notes with Python"
  author: "Kerry Back"
  date: "1/8/2023"
  chapters:
    - index.qmd
    - miracle.qmd
    
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: Chapter contents
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    
    



execute:
  freeze: auto


fig-cap-location: top

comments:
  hypothesis: true

